version: '3.8'
services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: self_management

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: self_management
    ports:
      - "5432:5432"
    volumes:
      - ./db/migration.sql:/docker-entrypoint-initdb.d/migration.sql