version: '3'
services:
  db:
    image: postgres:15
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
