services:
  db:
    image: postgres:16-bookworm
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: self_management
      TZ: "Asia/Tokyo"
    volumes:
      - dev-db:/var/lib/postgresql/data
    # 開発ツールから直接つなぎたいので開発では公開、本番では閉じてOK
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    # 開発はローカルビルド／本番は image: ghcr.io/.. に差し替えでOK
    build: .
    restart: always
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: self_management
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    # ← エントリポイント（entrypoint.sh）がイメージ内にある前提
    #    ここでは override で migrations をマウントしてホット反映します

volumes:
  dev-db:
