name: Build & Push for Raspberry Pi (multi-arch)

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/taskara:latest
            ghcr.io/${{ github.repository_owner }}/taskara:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
